// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0BuE2ZlIoEf64zMu6jvlbaI2NlmMlE8',
    appId: '1:1043142294768:web:5e6432e1c22a9fae0a5635',
    messagingSenderId: '1043142294768',
    projectId: 'trappra-chat-b51f7',
    authDomain: 'trappra-chat-b51f7.firebaseapp.com',
    storageBucket: 'trappra-chat-b51f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXvO85tvQBSWBYcXq03VjbKLmkA9vGxMQ',
    appId: '1:1043142294768:android:4af5bfcc7af5191b0a5635',
    messagingSenderId: '1043142294768',
    projectId: 'trappra-chat-b51f7',
    storageBucket: 'trappra-chat-b51f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_IYSr2VPuamFD6JZxB5_ArBLEPnvRJfg',
    appId: '1:1043142294768:ios:0793a6c1e2959eef0a5635',
    messagingSenderId: '1043142294768',
    projectId: 'trappra-chat-b51f7',
    storageBucket: 'trappra-chat-b51f7.appspot.com',
    iosClientId: '1043142294768-19q7d1vuvhark04umdglkq51mcc2reps.apps.googleusercontent.com',
    iosBundleId: 'com.example.trappraChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_IYSr2VPuamFD6JZxB5_ArBLEPnvRJfg',
    appId: '1:1043142294768:ios:9a4a3a070c1e4c370a5635',
    messagingSenderId: '1043142294768',
    projectId: 'trappra-chat-b51f7',
    storageBucket: 'trappra-chat-b51f7.appspot.com',
    iosClientId: '1043142294768-rpkra15mi6lefa47pcfb70vicr8pmp2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.trappraChat.RunnerTests',
  );
}
